### ISSUE TITLE
error of Openms in KNIME

### ISSUE THREAD

**Issue by hello-lei** [alexandrovteam/LCMS#12]
![image](https://user-images.githubusercontent.com/83147334/119251291-85f9c200-bbd8-11eb-8853-273b2f358efd.png)
This is a error,and I try again according the suggestion.
But It is doesnot work

**Comment by theodev** [comment]
Hi @hello-lei , 

Sorry we stopped supporting Optimus. I propose you to look into using mzMine for preparing data for `ili, and contact the Dorrestein Lab at UCSD for examples and help. 

Cheers

**Comment by hello-lei** [comment]
ok,thank for your suggestions I will try it.
